# Generated by Django 5.1.4 on 2025-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
