# Generated by Django 5.1.4 on 2025-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customer_mobile_alter_customer_mobile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
