# Generated by Django 5.1.4 on 2025-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_customer_mobile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user-images/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
