# Generated by Django 5.1.4 on 2025-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_imageupload_image_alter_imageupload_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phn',
            field=models.CharField(max_length=20),
        ),
    ]
