# Generated by Django 5.1.4 on 2025-03-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_contact_phn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user-images/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
