# Generated by Django 5.1.4 on 2025-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_cart_image_cart_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_customer_images/'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
