# Generated by Django 5.1.4 on 2025-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_cart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
