# Generated by Django 5.1.4 on 2025-03-06 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_staticpage_image'),
        ('userapp', '0011_alter_cart_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'image', 'text')},
        ),
    ]
