# Generated by Django 5.1.4 on 2025-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsliders',
            name='show_text',
            field=models.BooleanField(default=False),
        ),
    ]
