# Generated by Django 5.1.4 on 2025-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_backgroundsliders_show_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_type',
            field=models.CharField(default='Category', max_length=50),
        ),
    ]
