# Generated by Django 5.1.4 on 2025-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_page/'),
        ),
    ]
